version: '3'

networks:
  my_network:
    driver: bridge

services:
  service1:
    build: ./service1
    networks:
      - my_network
    ports:
      - "5001:5001"
    container_name: service1-container

  service2:
    build: ./service2
    networks:
      - my_network
    ports:
      - "5002:5002"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - my_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    